### ISSUE TITLE
Migrate to webpack

### ISSUE THREAD

**Issue by TheLarkInn** [fedspendingtransparency/data-act-broker-web-app#346]
This would be a great use case for a React app built on gulp to be transitioned to using webpack instead and the peg impacts that come with it. 

We (the webpack team) are happy to help advise in this migration if interested.

**Comment by kevinli-work** [comment]
Hey @TheLarkInn, we switched over to Webpack for JS primarily for its code splitting functionality, but our Sass compiling is still built on our previous Gulp process. When I last looked into switching completely over, we weren't really sold on the idea of referencing our Sass in our JS, especially since Webpack was integrating with Gulp fine.

**Comment by TheLarkInn** [comment]
No sweat! If that ever changes let me know. We want to support ya'll or help if we can :)
